global:
  resolve_timeout: 5m
  http_config:
    follow_redirects: true
  telegram_api_url: https://api.telegram.org
route:
    receiver: telegram
    continue: false
    group_wait: 30s
    group_interval: 5m  
    repeat_interval: 2h

receivers:
    - name: telegram
      telegram_configs:
      - send_resolved: true
        http_config:
          follow_redirects: true
        api_url: https://api.telegram.org
        bot_token: CHANGE_TO_YOUR_TOKEN
        chat_id: CHANGE_TO_YOUR_CHAT_ID
        message: '{{ template "telegram.default.message" . }}'
        parse_mode: HTML 
templates: []
